apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'k8s-agent'
        vault.hashicorp.com/agent-inject-secret-wordpress-config: 'kv-secret/data/wordpress-credential'
        vault.hashicorp.com/agent-inject-template-wordpress-config: |
          {{- with secret "kv-secret/data/wordpress-credential" -}}
            export WORDPRESS_DB_HOST="{{ .Data.data.db_host }}"
            export WORDPRESS_DB_NAME="{{ .Data.data.db_name }}"
            export WORDPRESS_DB_USER="{{ .Data.data.db_username }}"
            export WORDPRESS_DB_PASSWORD="{{ .Data.data.db_password }}"
          {{- end }}
      labels:
        app: wordpress
    spec:
      serviceAccountName: k8s-agent
      containers:
        - image: wordpress
          command:
            - 'sh'
            - '-c'
          args:
            [
              'source /vault/secrets/wordpress-config && docker-entrypoint.sh apache2-foreground',
            ]
          name: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim
