apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-custom
  namespace: default
  labels:
    app: wp-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-custom
  template:
    metadata:
      labels:
        app: wp-custom
    spec:
      containers:
        - name: wp-deployment
          image: nnvu187/wordpress-custom:latest
          ports:
            - containerPort: 80
              name: wp-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wp-custom
spec:
  ports:
    - port: 80
  selector:
    app: wp-custom
  type: LoadBalancer
